# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.5


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [38]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
# Importando o NumPy
import numpy as np
array = np.arange(0, 1000000, 1)
list1 = range(0, 1000000)

In [39]:
%time list1 = list(map(lambda x: x*2, list1))

%time array = np.array(map(lambda x: x*2, array))

Wall time: 139 ms
Wall time: 0 ns


### Exercício 2

In [41]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
array = np.arange(0, 10)
for x in range(5, 9):
    array[x] = 0
array

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

### Exercício 3

In [45]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
matrix = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
matrix[1]

array([1, 1, 1])

### Exercício 4

In [55]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[:,1])
print(matrix[:,2])
print(matrix[0])
print(matrix[1])

[2 5]
[3 6]
[1 2 3]
[4 5 6]


### Exercício 5

In [58]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [59]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
for x in range(0, 5):
    if cond[x]:
        print(xarr[x])
    else:
        print(yarr[x])

1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [60]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
arrayA = np.arange(0, 10)
np.save('arrayA',arrayA)
arrayB = np.load('arrayA.npy')
arrayB

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [61]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [64]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
data = resp.json()
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    40322  ENH: Method interface for selecting columns fr...   
1    40321                  BUG: read_excel leads to segfault   
2    40320         STYLE: Extending codespell to pandas/tests   
3    40319                         STYLE use pd_array in core   
4    40318  BUG: unexpected DataFrame output when LaTeX is...   
5    40317  PERF: reduce overhead in groupby _cython_opera...   
6    40316  BUG: Inserting series into dataframe does igno...   
7    40315  BUG: Inconsistent rounding up and rounding dow...   
8    40314  ERR: Raise NotImplimentedError for EWMA with t...   
9    40313  BUG: incorrect calculation of centered moving ...   
10   40312  [WIP] API: `Styler.to_html` can ultimately rep...   
11   40309  BUG: I am facing parse error but it was note r...   
12   40307       Use oldest-supported-numpy in pyproject.toml   
13   40306            REF: de-duplicate code for pad/backfill   
14   40305                     docs: changes to documentation   
15   40304  [ArrayManager] Add Series._as_manager (consoli...   
16   40303  [ArrayManager] Enable read_parquet to not crea...   
17   40300  PERF: further improve take (reindex/unstack) f...   
18   40299  PERF: get_dummies create array of 0/1s with ap...   
19   40298                [ArrayManager] TST: enable IO tests   
20   40296  ENH: add fast DataFrame iterator that doesn't ...   
21   40293                                   TYP: Window code   
22   40291  EHN: Refactor pd.read_excel/DataFrame.to_excel...   
23   40289  BUG: Inconsistent behaviour between excel engi...   
24   40288  DEPR: Series/DataFrame.transform partial failu...   
25   40287  ENH: IO support for R data files with `pandas....   
26   40286             STYLE: Resolved Inconsistent namespace   
27   40285    BLD: GH30873 Workaround parallel build failures   
28   40275                   POC: aggregate always aggregates   
29   40274  ENH: read_excel (xlrd engine) add parameter fo...   

                                               labels state  
0   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2                                                  []  open  
3   [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
7   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
8   [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
9   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
10                                                 []  open  
11  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
12  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
13  [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
14  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
15  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open  
16  [{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...  open  
17  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
18  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open  
19  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open  
20  [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
21  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
22  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
24  [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
25  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
26  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
27                                                 []  open  
28  [{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...  open  
29  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open

### Exercício 10

In [65]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [66]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [67]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [68]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>